# This is a basic workflow to help you get started with Actions
name: CoreTest - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!


    - name: auto test
      run: |
        name=wxg
        echo test begin > out.txt
        for test in $(ls ./testcase) 
        do
            echo "$test begin" >> out.txt
            java -jar qs.jar <./testcase/$test >qs.txt
            java -jar $name.jar <./testcase/$test >$name.txt
            diff -y -W  200 qs.txt $name.txt > diff.txt

            if [ $? -ne 0 ] ; then
                echo "WA" >> out.txt
                cat diff.txt >> out.txt
                exit 1
            else
                echo "AC" >> out.txt
            fi
        done
        echo "AK" >> out.txt
